// =======================================================
// ★★★ 2025年度南陵祭 公式企画データ ★★★
// =======================================================

// 企画の名簿データ (変更なし)
const projectData = [
    // --- 4階 ---
    {
        id: '1-1',
        name: '1年1組「タケムランド」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 160,
        mapY: 833,
        tags: ['1年生', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '1-2',
        name: '1年2組「赤字のカジノ ~ちょっぴり大人な休憩所~」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 362,
        mapY: 833,
        tags: ['1年生', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '1-3',
        name: '1年3組「中村縁日 ~射的でストレス発散~」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 574,
        mapY: 833,
        tags: ['1年生', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '1-4',
        name: '1年4組「あの子はどこ? ~次々といなくなる不可解な事件~」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 784,
        mapY: 833,
        tags: ['1年生', 'お化け屋敷'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '1-5',
        name: '1年5組「メイド喫茶ひさし」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 998,
        mapY: 833,
        tags: ['1年生', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '1-6',
        name: '1年6組「前園のハッピーライド」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 2034,
        mapY: 833,
        tags: ['1年生', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '1-7',
        name: '1年7組「MADE in MENDY」',
        catchphrase: '',
        place: '4階',
        floor: 4,
        mapX: 2240,
        mapY: 833,
        tags: ['1年生', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: 'election-corner',
        name: '選挙コーナー「選挙の投票体験」',
        catchphrase: '',
        place: '4階 選択教室1',
	locationId: 'ec1',
        floor: 4,
        mapX: 1823,
        mapY: 833,
        tags: ['その他', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'megumi',
        name: '横田めぐみさん「拉致被害者 横田めぐみさんに関する展示」',
        catchphrase: '',
        place: '4階 選択教室1',
	locationId: 'ec1',
        tags: ['その他', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },

    // --- 3階 ---
    {
        id: '2-1',
        name: '2年1組「13年前の校舎」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 162,
        mapY: 833,
        tags: ['2年生', 'お化け屋敷'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '2-2',
        name: '2年2組「ROUND2」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 372,
        mapY: 833,
        tags: ['2年生', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '2-3',
        name: '2年3組「ボードゲームカフェ ~SUGURU~」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 573,
        mapY: 833,
        tags: ['2年生', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '2-4',
        name: '2年4組「Club楓」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 788,
        mapY: 833,
        tags: ['2年生', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '2-5',
        name: '2年5組「純喫茶ナオヤとヒカル兄やん。」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 992,
        mapY: 833,
        tags: ['2年生', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '2-6',
        name: '2年6組「ナベ病院 ~開かずの診察室~」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 1611,
        mapY: 833,
        tags: ['2年生', 'お化け屋敷'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: '2-7',
        name: '2年7組「?Melty めいど?」',
        catchphrase: '',
        place: '3階',
        floor: 3,
        mapX: 1816,
        mapY: 833,
        tags: ['2年生', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: 'biology-club',
        name: '生物部「生物部」',
        catchphrase: '',
        place: '3階 生物室',
        floor: 3,
        mapX: 162,
        mapY: 1431,
        tags: ['部活動・同好会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'art-club',
        name: '美術部「展示発表会」',
        catchphrase: '',
        place: '3階 美術室',
        floor: 3,
        mapX: 1757,
        mapY: 1292,
	locationId: 'art-room', 
        tags: ['部活動・同好会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'art-course',
        name: '美術科「美術科 授業制作作品展示」',
        catchphrase: '',
        place: '3階 美術室',
        floor: 3,
	locationId: 'art-room', 
        tags: ['その他', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    
    // --- 2階 ---
    {
        id: 'game-club-room', // ★IDをステージ発表と区別するために変更
        name: 'ゲーム同好会「南陵スマブラ王決定戦」',
        catchphrase: '',
        place: '2階',
        floor: 2,
        mapX: 573,
        mapY: 833,
        tags: ['部活動・同好会', '体験・ゲーム'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'tea-ceremony-club',
        name: '茶道部「夏果の茶会~ふらっと茶縁日和~」',
        catchphrase: '',
        place: '2階',
        floor: 2,
        mapX: 2271,
        mapY: 867,
        tags: ['部活動・同好会', 'カフェ'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'literature-club',
        name: '文芸同好会「丸い鈴に隠された物語 ~あらすじを辿って~」',
        catchphrase: '',
        place: '2階',
        floor: 2,
        mapX: 783,
        mapY: 833,
        tags: ['部活動・同好会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'manga-club',
        name: '漫画研究部「The future day break」',
        catchphrase: '',
        place: '2階',
        floor: 2,
        mapX: 998,
        mapY: 833,
        tags: ['部活動・同好会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'disaster-prevention-committee',
        name: '防災委員「高めよう防災意識」',
        catchphrase: '',
        place: '2階廊下',
        floor: 2,
        mapX: 1492,
        mapY: 968,
        tags: ['委員会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'calligraphy-course',
        name: '書道科「書道展2025」',
        catchphrase: '',
        place: '2階 書道室',
        floor: 2,
        mapX: 1752,
        mapY: 1301,
        tags: ['その他', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'cs-club',
        name: 'コンピューター科学部「南稜文化祭ホームページ」',
        catchphrase: '',
        place: '2階',
        floor: 2,
        mapX: null,
        mapY: null,
        tags: ['部活動・同好会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
    {
        id: 'pta',
        name: 'PTA「Nanryo Mart」',
        catchphrase: '',
        place: '2階',
        floor: 2,
        mapX: 366,
        mapY: 833,
        tags: ['その他', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },

    // --- 5階 ---
    {
        id: 'library-committee',
        name: '図書委員「天球の図書館」',
        catchphrase: '',
        place: '5階 図書館',
        floor: 5,
        mapX: 2235,
        mapY: 874,
        tags: ['委員会', '展示'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },

    // --- 外/ピロティ/昇降口など (便宜上1階として扱います) ---
    {
        id: '3-1-food',
        name: '3年1組「フランクフルト」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 367,
        mapY: 1238,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '3-2-food',
        name: '3年2組「たこってかない?」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 367,
        mapY: 1128,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '3-3-food',
        name: '3年3組「ケバブ」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 2124,
        mapY: 1452,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '3-4-food',
        name: '3年4組「やきとり」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 367,
        mapY: 1348,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '3-5-food',
        name: '3年5組「畠山が認めた三ツ星炭火焼き店」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 2124,
        mapY: 1550,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '3-6-food',
        name: '3年6組「そばにいて。」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 2124,
        mapY: 1350,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: '3-7-food',
        name: '3年7組「豚串こみちゃん」',
        catchphrase: '',
        place: '外テント',
        floor: 1,
        mapX: 598,
        mapY: 1128,
        tags: ['3年生', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: 'home-making-club',
        name: 'ホームメイキング部「手作りお菓子の販売」',
        catchphrase: '',
        place: 'ピロティ(外)',
        floor: 1,
        mapX: 1993,
        mapY: 879,
        tags: ['部活動・同好会', '販売'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'menu',
        menu: []
    },
    {
        id: 'student-council',
        name: '生徒会「南陵祭部門別ランキング」',
        catchphrase: '',
        tags: ['その他', 'その他'],
        description: '',
        image: 'images/placeholder.jpg',
        contentType: 'gallery',
        gallery: []
    },
];


// =======================================================
// ★★★ ステージ発表のデータ (シンプル版・完成形) ★★★
// =======================================================
const stageData = [
    // --- DAY 1 ---
    {
        id: 'day1-keion-1',
        groupId: 'keion',
        groupName: '軽音楽部',
        name: 'ライブ',
        place: '体育館',
        locationId: 'gymnasium',
        time: '10:30 - 11:20',
        tags: ['DAY1', 'ステージ', '音楽', '部活動'],
        groupDescription: '私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！',
        image: 'images/group-keion.jpg'
    },
    {
        id: 'day1-shafuku',
        groupId: 'shafuku',
        groupName: '社会福祉部',
        name: '発表',
        place: '体育館',
        locationId: 'gymnasium',
        time: '11:45 - 12:05',
        tags: ['DAY1', 'ステージ', '発表', '部活動'],
        groupDescription: '社会福祉部の活動について発表します。私たちの取り組みをぜひご覧ください。',
        image: 'images/group-shafuku.jpg'
    },
    {
        id: 'day1-keion-2',
        groupId: 'keion',
        groupName: '軽音楽部',
        name: 'ライブ',
        place: '3階視聴覚室',
        locationId: 'av-room',
        time: '12:00 - 15:00',
        tags: ['DAY1', 'ステージ', '音楽', '部活動'],
        groupDescription: '私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！',
        image: 'images/group-keion.jpg'
    },
    {
        id: 'day1-danbasu',
        groupId: 'danbasu',
        groupName: '男子バスケ部',
        name: 'パフォーマンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '12:20 - 12:45',
        tags: ['DAY1', 'ステージ', 'パフォーマンス', '部活動'],
        groupDescription: '男子バスケットボール部が、コートを離れてステージでスペシャルパフォーマンスを披露します！お楽しみに！',
        image: 'images/group-danbasu.jpg'
    },
    {
        id: 'day1-gunma',
        groupId: 'gunma',
        groupName: 'ぐんまさ',
        name: 'パフォーマンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '13:10 - 13:20',
        tags: ['DAY1', 'ステージ', 'パフォーマンス', '有志'],
        groupDescription: '有志団体「ぐんまさ」によるスペシャルパフォーマンスです！',
        image: 'images/group-yushi.jpg'
    },
    {
        id: 'day1-aomito-1',
        groupId: 'aomito',
        groupName: 'あおみと',
        name: 'パフォーマンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '13:30 - 13:40',
        tags: ['DAY1', 'ステージ', 'パフォーマンス', '有志'],
        groupDescription: '有志団体「あおみと」によるスペシャルパフォーマンスです！',
        image: 'images/group-yushi.jpg'
    },
    {
        id: 'day1-suibu',
        groupId: 'suibu',
        groupName: '吹奏楽部',
        name: 'コンサート',
        place: '4階 音楽室',
        locationId: 'music-room',
        time: '13:30 - 14:15',
        tags: ['DAY1','ステージ', '音楽', '部活動'],
        groupDescription: '吹奏楽部によるミニコンサートです。両日とも音楽室で開催します。美しいハーモニーをお楽しみください。',
        image: 'images/group-suibu.jpg'
    },
    {
        id: 'day1-modern-dance',
        groupId: 'moderndance',
        groupName: 'モダンダンス部',
        name: 'ダンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '14:10 - 15:00',
        tags: ['DAY1', 'ステージ', 'ダンス', '部活動'],
        groupDescription: 'モダンダンス部による情熱的なパフォーマンスにご期待ください。両日とも体育館で発表します！',
        image: 'images/group-moderndance.jpg'
    },
    
    // --- DAY 2 ---
    {
        id: 'day2-soukyoku',
        groupId: 'soukyoku',
        groupName: '箏曲部',
        name: '演奏会',
        place: '体育館',
        locationId: 'gymnasium',
        time: '10:30 - 11:00',
        tags: ['DAY2', 'ステージ', '音楽', '部活動'],
        groupDescription: '箏曲部による、和の美しい音色をお楽しみください。',
        image: 'images/group-soukyoku.jpg'
    },
    {
        id: 'day2-keion-3',
        groupId: 'keion',
        groupName: '軽音楽部',
        name: 'ライブ',
        place: '3階視聴覚室',
        locationId: 'av-room',
        time: '10:00 - 13:00',
        tags: ['DAY2', 'ステージ', '音楽', '部活動'],
        groupDescription: '私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！',
        image: 'images/group-keion.jpg'
    },
    {
        id: 'day2-danbasu',
        groupId: 'danbasu',
        groupName: '男子バスケ部',
        name: 'パフォーマンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '11:00 - 11:25',
        tags: ['DAY2', 'ステージ', 'パフォーマンス', '部活動'],
        groupDescription: '男子バスケットボール部が、コートを離れてステージでスペシャルパフォーマンスを披露します！お楽しみに！',
        image: 'images/group-danbasu.jpg'
    },
    {
        id: 'day2-game',
        groupId: 'game',
        groupName: 'ゲーム同好会',
        name: 'ステージ',
        place: '体育館',
        locationId: 'gymnasium',
        time: '11:25 - 11:40',
        tags: ['DAY2', 'ステージ', '発表', '部活動'],
        groupDescription: 'ゲーム同好会です！2階でのスマブラ大会に加えて、体育館ステージでも活動紹介を行います！',
        image: 'images/group-game.jpg'
    },
    {
        id: 'day2-shafuku',
        groupId: 'shafuku',
        groupName: '社会福祉部',
        name: '発表',
        place: '体育館',
        locationId: 'gymnasium',
        time: '11:40 - 12:00',
        tags: ['DAY2', 'ステージ', '発表', '部活動'],
        groupDescription: '社会福祉部の活動について発表します。私たちの取り組みをぜひご覧ください。',
        image: 'images/group-shafuku.jpg'
    },
    {
        id: 'day2-gunma',
        groupId: 'gunma',
        groupName: 'ぐんまさ',
        name: 'パフォーマンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '12:00 - 12:10',
        tags: ['DAY2', 'ステージ', 'パフォーマンス', '有志'],
        groupDescription: '有志団体「ぐんまさ」によるスペシャルパフォーマンスです！',
        image: 'images/group-yushi.jpg'
    },
    {
        id: 'day2-aomito-2',
        groupId: 'aomito',
        groupName: 'あおみと',
        name: 'パフォーマンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '12:10 - 12:20',
        tags: ['DAY2', 'ステージ', 'パフォーマンス', '有志'],
        groupDescription: '有志団体「あおみと」によるスペシャルパフォーマンスです！',
        image: 'images/group-yushi.jpg'
    },
    {
        id: 'day2-dancingjk',
        groupId: 'dancingjk',
        groupName: 'ダンシングJK',
        name: 'ダンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '12:20 - 13:00',
        tags: ['DAY2', 'ステージ', 'ダンス', '有志'],
        groupDescription: '有志団体「ダンシングJK」による、パワフルなダンスステージ！',
        image: 'images/group-yushi.jpg'
    },
    {
        id: 'day2-chorus',
        groupId: 'chorus',
        groupName: 'コーラス部',
        name: 'コンサート',
        place: '4階 音楽室',
        locationId: 'music-room',
        time: '12:30 - 13:30',
        tags: ['DAY2', 'ステージ', '音楽', '部活動'],
        groupDescription: 'コーラス部による美しい歌声が音楽室に響き渡ります。ぜひ聴きに来てください。',
        image: 'images/group-chorus.jpg'
    },
    {
        id: 'day2-modern-dance',
        groupId: 'moderndance',
        groupName: 'モダンダンス部',
        name: 'ダンス',
        place: '体育館',
        locationId: 'gymnasium',
        time: '13:00 - 13:50',
        tags: ['DAY2', 'ステージ', 'ダンス', '部活動'],
        groupDescription: 'モダンダンス部による情熱的なパフォーマンスにご期待ください。両日とも体育館で発表します！',
        image: 'images/group-moderndance.jpg'
    },
    {
        id: 'day2-suibu',
        groupId: 'suibu',
        groupName: '吹奏楽部',
        name: 'コンサート',
        place: '4階 音楽室',
        locationId: 'music-room',
        time: '13:30 - 14:15',
        tags: ['DAY2', 'ステージ', '音楽', '部活動'],
        groupDescription: '吹奏楽部によるミニコンサートです。両日とも音楽室で開催します。美しいハーモニーをお楽しみください。',
        image: 'images/group-suibu.jpg'
    },
    {
        id: 'day2-keion-4',
        groupId: 'keion',
        groupName: '軽音楽部',
        name: 'ライブ',
        place: '体育館',
        locationId: 'gymnasium',
        time: '14:10 - 15:00',
        tags: ['DAY2', 'ステージ', '音楽', '部活動'],
        groupDescription: '私たち軽音楽部は、最高の音楽で文化祭を盛り上げます！体育館ステージと視聴覚室の両方でライブを行うので、ぜひ見に来てください！',
        image: 'images/group-keion.jpg'
    },
    // --- 以下は場所の情報なので、変更なし ---
    {
        id: 'place-gym',
        name: '体育館ステージ',
        place: '体育館',
        locationId: 'gymnasium', 
        hubType: 'primary',
        floor: 1, 
        mapX: 1014,
        mapY: 1327,  
        catchphrase: '文化祭のメインステージ！',
        description: '熱いパフォーマンスが繰り広げられるメインステージです。タイムテーブルをチェック！',
        tags: ['ステージ', 'ステージ'],
        image: 'images/gym-stage.jpg' 
    },
    {
        id: 'place-av-room',
        name: '視聴覚室ライブ',
        place: '3階 視聴覚室',
        locationId: 'av-room',
        floor: 3,
        mapX: 1300,
        mapY: 570,  
        hubType: 'secondary',
        catchphrase: 'ライブハウスはこちら！',
        description: '熱いライブが繰り広げられるサブステージです。タイムテーブルをチェック！',
        tags: ['ステージ'],
        image: 'images/av-room.jpg'
    },
    {
        id: 'place-music-room',
        name: '音楽室コンサート',
        place: '4階 音楽室',
        locationId: 'music-room',
        floor: 4,
        mapX: 1752,
        mapY: 1300,
        hubType: 'secondary',
        catchphrase: '美しい音色が響き渡る。',
        tags: ['ステージ'],
        image: 'images/music-room.jpg'
    }
];
